global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'notification-client'
    static_configs:
      - targets: ['notification-client:8181']
    metrics_path: '/metrics'